source 'https://rubygems.org'

# RAILS
gem 'rails', '~> 5.1.0' # Bundle edge Rails instead: gem 'rails', github: 'rails/rails'
gem 'mongoid', '6.3.0'
gem 'mongoid_rails_migrations', '1.1.0'
gem 'mongoid_search'
gem 'mongoid-tree'
gem 'puma', '~> 3.10' # Use Puma as the app server

# ASSETS
gem 'carrierwave', '1.0.0'
gem 'carrierwave-mongoid'
gem 'coffee-rails' # Use CoffeeScript for .coffee assets and views
gem 'haml-rails'
gem 'jquery-rails' # Use jquery as the JavaScript library
gem 'kaminari-mongoid'
gem 'kaminari-actionview'
gem 'rails-i18n'
# gem 'mini_magick'
gem 'rmagick'
gem 'sass-rails', '~> 5.0' # Use SCSS for stylesheets
gem 'turbolinks', '~> 5' # Turbolinks makes navigating your web application faster. Read more: https://github.com/turbolinks/turbolinks
gem 'uglifier', '>= 1.3.0' # Use Uglifier as compressor for JavaScript assets

# API
gem 'active_model_serializers', '0.10.2'
# gem 'doorkeeper-mongodb', github: 'doorkeeper-gem/doorkeeper-mongodb'
# gem 'doorkeeper-mongodb', github: 'fuerstenberg/doorkeeper-mongodb'
gem 'doorkeeper', '5.0.2'
gem 'doorkeeper-mongodb', '5.0.0'

gem 'rack-cors', require: 'rack/cors'

# Authentication and autorization
gem 'devise'

# OTHERS
gem 'access-granted'
gem 'geocoder', '1.3.7'
gem 'responders', '~> 2.4'
gem 'therubyracer', '0.12.3'

# REVIEW: is it really needed???
# gem 'jbuilder', '~> 2.5' # Build JSON APIs with ease. Read more: https://github.com/rails/jbuilder

# Use Redis adapter to run Action Cable in production
# gem 'redis', '~> 3.0'
# Use ActiveModel has_secure_password
# gem 'bcrypt', '~> 3.1.7'

# gem 'therubyracer'

gem 'airbrake', '~> 5.6.1'

gem 'sdoc', '~> 0.4.0', group: :doc # bundle exec rake doc:rails generates the API under doc/api.

group :development, :test do
  gem 'byebug', platform: :mri # Call 'byebug' anywhere in the code to stop execution and get a debugger console
  gem 'database_cleaner'
  gem 'factory_bot_rails'
  gem 'json-schema'
  gem 'mongoid-rspec'
  gem 'rspec-rails'
  gem 'simplecov', require: false
end

group :development do
  gem 'capistrano', '3.5.0'
  gem 'capistrano-rails', '1.1.7'
  gem 'capistrano-rvm'
  gem 'capistrano-bundler'
  gem 'capistrano-passenger'
  gem 'guard-rspec', require: false
  gem 'listen', '~> 3.0.5'
  # gem 'spring' # Spring speeds up development by keeping your application running in the background. Read more: https://github.com/rails/spring
  # gem 'spring-watcher-listen', '~> 2.0.0'
  gem 'web-console' # Access an IRB console on exception pages or by using <%= console %> anywhere in the code.
end
