source 'https://rubygems.org'

gem 'rails',                      '4.2.7'

# TODO: gem 'acts-as-messageable', git: 'git://github.com/LTe/acts-as-messageable.git', branch: 'master'
# TODO: gem 'acts-as-taggable-on'
gem 'access-granted',             '1.2.0'
gem 'active_model_serializers',   '0.10.6'
gem 'airbrake',                   '5.4.1'
gem 'amistad'
gem 'auto_html',                  '2.0.0'
gem 'autoprefixer-rails'
# gem 'bootstrap-sass',             '3.3.6'
gem 'bootstrap',                  '~> 4.0.0.alpha6'
gem 'bourbon'
gem 'carrierwave-mongoid'
gem 'coffee-rails'
gem 'daemons',                    '1.1.9'
gem 'dalli' # High performance memcached client for Ruby
gem 'delayed_job_mongoid'
gem 'devise',                     '4.2.0'
gem 'devise-encryptable',         '0.2.0'
gem 'enumerize'
gem 'font-awesome-sass',          '~> 4.7.0'
gem 'geocoder',                   '1.6.1'
gem 'gon'
gem 'haml-rails'
gem 'has_scope'
gem 'i18n'
gem 'jbuilder',                   '~> 1.2' # Build JSON APIs with ease. Read more: https://github.com/rails/jbuilder
gem 'jquery-rails',               '3.1.0'                # Use jquery as the JavaScript library
gem 'jquery-ui-rails',            '4.2.0'                # https://github.com/joliss/jquery-ui-rails
gem 'kaminari-mongoid'
gem 'kaminari-actionview'
gem 'koala'
gem 'memcache-client'
gem 'metainspector'
gem 'mini_magick'
gem 'mongoid_rails_migrations'
gem 'mongoid',                    '5.2.0'
gem 'mongoid-history'
gem 'mongoid_search'
gem 'nokogiri',                   '1.6.0'
gem 'omniauth-facebook',          '4.0.0'
gem 'opengraph_parser'
gem 'public_activity'
# gem 'rack-ssl-enforcer'
gem 'sass-rails'
gem 'sidekiq'
gem 'slack-notifier'
gem 'sprockets-rails'
gem 'stringex'
gem 'therubyracer',               '0.12.0'
gem 'turbolinks',                 '2.5.3'                # Turbolinks makes following links in your web application faster. Read more: https://github.com/rails/turbolinks
gem 'uglifier',                   '>= 1.3.0'             # Use Uglifier as compressor for JavaScript assets
gem 'whenever', require: false
gem 'wombat',                     '2.3.0'
gem 'youtube_it'
gem 'chartkick'

source 'https://rails-assets.org' do
  gem 'rails-assets-tether', '>= 1.3.3'
end

group :doc do
  gem 'sdoc', require: false                      # bundle exec rake doc:rails generates the API under doc/api.
end

group :development, :test do
  gem 'byebug'
  gem 'capybara',           '2.4.1'
  gem 'capybara-webkit',    '1.3.0'
  gem 'database_cleaner'
  gem 'factory_girl_rails', '4.2.1'
  gem 'launchy',            '2.4.2'
  gem 'mongoid-rspec',      '3.0.0'
  gem 'rb-fsevent'
  gem 'rspec-rails'
  gem 'turnip'
end

group :development do
  gem 'better_errors'
  gem 'binding_of_caller'
  gem 'capistrano',         '3.4.0'
  gem 'capistrano-rails',   '1.1.7'
  gem 'capistrano-bundler'
  gem 'quiet_assets'
end

# gem 'daemons',                    '1.1.8'
# gem 'dalli'
# gem 'execjs',                     '1.3.0'
# gem 'i18n'
# gem 'modernizr-rails'
# gem 'redcarpet',                  '2.1.1'
# gem 'rvm-capistrano'
# gem 'state_machine',              '1.1.2'
# gem 'uglifier',         '>= 1.3.0'
